title: "Simple Object-Oriented Design: A guide to creating clean, maintainable code, by Maurício Aniche"
description: "Simple Object-Oriented Design is a book written by Maurício Aniche and published by Manning"
keywords: "mauricio aniche, simple object-oriented design"
url: http://www.simple-object-oriented-design.com

theme: null
permalink: /:title

destination: _site
future: false

buy_url: "https://www.manning.com/books/simple-object-oriented-design"

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
